(task_manager-1o44OnFQ) martin@tintin:~/Project/task_manager/task_manager$ python seed.py
Traceback (most recent call last):
  File "/home/martin/Project/task_manager/task_manager/seed.py", line 48, in <module>
    user_id = user_ids[username]
KeyError: 'Linda Ochoa'

due to not keys
tasks = []
for category in categories:
    username = fake.random_element(elements=new_usernames)
    task = Task(description=category.description, 
                priority=fake.random_element(elements=('Low', 'Medium', 'High')), 
                username=username, 
                category_id=category.id,
                # user_id = user_ids[username]
    )